export const courses = [
  {
    code: "ME5104",
    title: "Computational Fluid Dynamics & Programming",
    level: "PG",
    semester: "Fall 2025",
    university: "MU",
    slug: "me5104",
  },
  {
    code: "ME5001",
    title: "Turbulent Flows",
    level: "PG",
    semester: "Spring 2026",
    university: "MU",
    slug: "me5001",
  },
  {
    code: "ME5201",
    title: "Multiphysics",
    level: "PG",
    semester: "Spring 2026",
    university: "MU",
    slug: "me5201",
  },
  {
    code: "ME5204",
    title: "CFD Lab",
    level: "PG",
    semester: "Spring 2026",
    university: "MU",
    slug: "me5204",
  },
  {
    code: "ME2233",
    title: "Aerodynamics I",
    level: "UG",
    semester: "Spring 2026",
    university: "MU",
    slug: "me2233",
  },
  {
    code: "APPM2360",
    title: "Intro to Differential Equations with Linear Algebra",
    level: "UG",
    semester: "Fall 2021 – Spring 2024",
    university: "CU",
    slug: "appm2360",
  },
];
